# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Liz Holm's Research Group
email: eaholm@andrew.cmu.edu
description: > # this means to ignore newlines until "baseurl:"
  Liz Holm leads a computational research group focused on atomistic and mesoscale modeling and informatics in the CMU Materials Science and Engineering department.
baseurl: "" # the subpath of your site, e.g. /blog
url: "holmgroup.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  holmgroup
cmu_url: http://www.cmu.edu/engineering/materials/people/faculty/bios/holm.html
author: "Professor Elizabeth A. Holm"

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
